CREATE TABLE IF NOT EXISTS `infected` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`round` INT, 
`team` INT, 
`map` varchar(64), 
`steamid` varchar(32), 
`deleted` BOOLEAN, 
`isSecondHalf` BOOLEAN, 
`infDmgTotal` INT, 
`infDmgUpright` INT, 
`infDmgTank` INT, 
`infDmgTankIncap` INT, 
`infDmgScratch` INT, 
`infDmgScratchSmoker` INT, 
`infDmgScratchBoomer` INT, 
`infDmgScratchHunter` INT, 
`infDmgScratchCharger` INT, 
`infDmgScratchSpitter` INT, 
`infDmgScratchJockey` INT, 
`infDmgSpit` INT, 
`infDmgBoom` INT, 
`infDmgTankUp` INT, 
`infHunterDPs` INT, 
`infHunterDPDmg` INT, 
`infJockeyDPs` INT, 
`infDeathCharges` INT, 
`infCharges` INT, 
`infMultiCharges` INT, 
`infBoomsSingle` INT, 
`infBoomsDouble` INT, 
`infBoomsTriple` INT, 
`infBoomsQuad` INT, 
`infBooms` INT, 
`infBoomerPops` INT, 
`infLedged` INT, 
`infCommon` INT, 
`infSpawns` INT, 
`infSpawnSmoker` INT, 
`infSpawnBoomer` INT, 
`infSpawnHunter` INT, 
`infSpawnCharger` INT, 
`infSpawnSpitter` INT, 
`infSpawnJockey` INT, 
`infTankPasses` INT, 
`infTankRockHits` INT, 
`infCarsTriggered` INT, 
`infJockeyRideDuration` INT, 
`infJockeyRideTotal` INT, 
`infTimeStartPresent` INT, 
`infTimeStopPresent` INT, 
`infBoomsProxyTotal` INT, 
`infDmgTotalPerSpawn` NUMERIC(10, 5), 
`infDmgUprightPerSpawn` NUMERIC(10, 5), 
`infDmgTankPerSpawn` NUMERIC(10, 5), 
`infDmgTankIncapPerSpawn` NUMERIC(10, 5), 
`infDmgScratchPerSpawn` NUMERIC(10, 5), 
`infDmgScratchSmokerPerSpawn` NUMERIC(10, 5), 
`infDmgScratchBoomerPerSpawn` NUMERIC(10, 5), 
`infDmgScratchHunterPerSpawn` NUMERIC(10, 5), 
`infDmgScratchChargerPerSpawn` NUMERIC(10, 5), 
`infDmgScratchSpitterPerSpawn` NUMERIC(10, 5), 
`infDmgScratchJockeyPerSpawn` NUMERIC(10, 5), 
`infDmgSpitPerSpawn` NUMERIC(10, 5), 
`infDmgBoomPerSpawn` NUMERIC(10, 5), 
`infDmgTankUpPerSpawn` NUMERIC(10, 5), 
`infHunterDPsPerSpawn` NUMERIC(10, 5), 
`infHunterDPDmgPerSpawn` NUMERIC(10, 5), 
`infDeathChargesPerSpawn` NUMERIC(10, 5), 
`infChargesPerSpawn` NUMERIC(10, 5), 
`infMultiChargesPerSpawn` NUMERIC(10, 5), 
`infBoomsSinglePerSpawn` NUMERIC(10, 5), 
`infBoomsDoublePerSpawn` NUMERIC(10, 5), 
`infBoomsTriplePerSpawn` NUMERIC(10, 5), 
`infBoomsQuadPerSpawn` NUMERIC(10, 5), 
`infBoomsPerSpawn` NUMERIC(10, 5), 
`infBoomsProxyTotalPerSpawn` NUMERIC(10, 5), 
`infBoomerPopsPerSpawn` NUMERIC(10, 5), 
`infLedgedPerSpawn` NUMERIC(10, 5), 
`infTankRockHitsPerSpawn` NUMERIC(10, 5), 
`infCarsTriggeredPerSpawn` NUMERIC(10, 5), 
`infJockeyRideDurationPerSpawn` NUMERIC(10, 5), 
`infJockeyRideTotalPerSpawn` NUMERIC(10, 5), 
PRIMARY KEY  (`id`) 
);