CREATE TABLE IF NOT EXISTS `round` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`round` INT, 
`team` INT, 
`map` varchar(64), 
`deleted` BOOLEAN, 
`isSecondHalf` BOOLEAN, 
`teamIsA` BOOLEAN, 
`teamARound` INT, 
`teamATotal` INT, 
`teamBRound` INT, 
`teamBTotal` INT, 
`survivorCount` INT, 
`maxCompletionScore` INT, 
`maxFlowDist` INT, 
`rndRestarts` INT, 
`rndPillsUsed` INT, 
`rndKitsUsed` INT, 
`rndDefibsUsed` INT, 
`rndCommon` INT, 
`rndSIKilled` INT, 
`rndSIDamage` INT, 
`rndSISpawned` INT, 
`rndWitchKilled` INT, 
`rndTankKilled` INT, 
`rndIncaps` INT, 
`rndDeaths` INT, 
`rndFFDamageTotal` INT, 
`rndStartTime` INT, 
`rndEndTime` INT, 
`rndStartTimePause` INT, 
`rndStopTimePause` INT, 
`rndStartTimeTank` INT, 
`rndStopTimeTank` INT, 
`configName` varchar(64), 
PRIMARY KEY  (`id`) 
);