/* 
    Creates round, survivor, infected, matchlog, players, and maps tables
*/

DROP FUNCTION IF EXISTS rand_int;

DELIMITER //

CREATE FUNCTION rand_int(a INT, b INT) RETURNS INT DETERMINISTIC
BEGIN
    RETURN FLOOR(RAND()*(b-a+1))+a;
END //

DELIMITER ;

CREATE TABLE IF NOT EXISTS `round` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`round` INT, 
`team` INT, 
`map` varchar(64), 
`deleted` BOOLEAN, 
`isSecondHalf` BOOLEAN, 
`teamIsA` BOOLEAN, 
`teamARound` INT, 
`teamATotal` INT, 
`teamBRound` INT, 
`teamBTotal` INT, 
`survivorCount` INT, 
`maxCompletionScore` INT, 
`maxFlowDist` INT, 
`rndRestarts` INT, 
`rndPillsUsed` INT, 
`rndKitsUsed` INT, 
`rndDefibsUsed` INT, 
`rndCommon` INT, 
`rndSIKilled` INT, 
`rndSIDamage` INT, 
`rndSISpawned` INT, 
`rndWitchKilled` INT, 
`rndTankKilled` INT, 
`rndIncaps` INT, 
`rndDeaths` INT, 
`rndFFDamageTotal` INT, 
`rndStartTime` INT, 
`rndEndTime` INT, 
`rndStartTimePause` INT, 
`rndStopTimePause` INT, 
`rndStartTimeTank` INT, 
`rndStopTimeTank` INT, 
PRIMARY KEY  (`id`) 
);

CREATE TABLE IF NOT EXISTS `survivor` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`round` INT, 
`team` INT, 
`map` varchar(64), 
`steamid` varchar(32), 
`deleted` BOOLEAN, 
`isSecondHalf` BOOLEAN, 
`plyShotsShotgun` INT, 
`plyShotsSmg` INT, 
`plyShotsSniper` INT, 
`plyShotsPistol` INT, 
`plyHitsShotgun` INT, 
`plyHitsSmg` INT, 
`plyHitsSniper` INT, 
`plyHitsPistol` INT, 
`plyHeadshotsSmg` INT, 
`plyHeadshotsSniper` INT, 
`plyHeadshotsPistol` INT, 
`plyHeadshotsSISmg` INT, 
`plyHeadshotsSISniper` INT, 
`plyHeadshotsSIPistol` INT, 
`plyHitsSIShotgun` INT, 
`plyHitsSISmg` INT, 
`plyHitsSISniper` INT, 
`plyHitsSIPistol` INT, 
`plyHitsTankShotgun` INT, 
`plyHitsTankSmg` INT, 
`plyHitsTankSniper` INT, 
`plyHitsTankPistol` INT, 
`plyCommon` INT, 
`plyCommonTankUp` INT, 
`plySIKilled` INT, 
`plySIKilledTankUp` INT, 
`plySIDamage` INT, 
`plySIDamageTankUp` INT, 
`plyIncaps` INT, 
`plyDied` INT, 
`plySkeets` INT, 
`plySkeetsHurt` INT, 
`plySkeetsMelee` INT, 
`plyLevels` INT, 
`plyLevelsHurt` INT, 
`plyPops` INT, 
`plyCrowns` INT, 
`plyCrownsHurt` INT, 
`plyShoves` INT, 
`plyDeadStops` INT, 
`plyTongueCuts` INT, 
`plySelfClears` INT, 
`plyFallDamage` INT, 
`plyDmgTaken` INT, 
`plyDmgTakenBoom` INT, 
`plyDmgTakenCommon` INT, 
`plyDmgTakenTank` INT, 
`plyBowls` INT, 
`plyCharges` INT, 
`plyDeathCharges` INT, 
`plyFFGiven` INT, 
`plyFFTaken` INT, 
`plyFFHits` INT, 
`plyTankDamage` INT, 
`plyWitchDamage` INT, 
`plyMeleesOnTank` INT, 
`plyRockSkeets` INT, 
`plyRockEats` INT, 
`plyFFGivenPellet` INT, 
`plyFFGivenBullet` INT, 
`plyFFGivenSniper` INT, 
`plyFFGivenMelee` INT, 
`plyFFGivenFire` INT, 
`plyFFGivenIncap` INT, 
`plyFFGivenOther` INT, 
`plyFFGivenSelf` INT, 
`plyFFTakenPellet` INT, 
`plyFFTakenBullet` INT, 
`plyFFTakenSniper` INT, 
`plyFFTakenMelee` INT, 
`plyFFTakenFire` INT, 
`plyFFTakenIncap` INT, 
`plyFFTakenOther` INT, 
`plyFFGivenTotal` INT, 
`plyFFTakenTotal` INT, 
`plyCarsTriggered` INT, 
`plyJockeyRideDuration` INT, 
`plyJockeyRideTotal` INT, 
`plyClears` INT, 
`plyAvgClearTime` INT, 
`plyTimeStartPresent` INT, 
`plyTimeStopPresent` INT, 
`plyTimeStartAlive` INT, 
`plyTimeStopAlive` INT, 
`plyTimeStartUpright` INT, 
`plyTimeStopUpright` INT,
`plyCurFlowDist` INT,
`plyFarFlowDist` INT,
`plyProtectAwards` INT,
PRIMARY KEY  (`id`) 
);

CREATE TABLE IF NOT EXISTS `infected` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`round` INT, 
`team` INT, 
`map` varchar(64), 
`steamid` varchar(32), 
`deleted` BOOLEAN, 
`isSecondHalf` BOOLEAN, 
`infDmgTotal` INT, 
`infDmgUpright` INT, 
`infDmgTank` INT, 
`infDmgTankIncap` INT, 
`infDmgScratch` INT, 
`infDmgScratchSmoker` INT, 
`infDmgScratchBoomer` INT, 
`infDmgScratchHunter` INT, 
`infDmgScratchCharger` INT, 
`infDmgScratchSpitter` INT, 
`infDmgScratchJockey` INT, 
`infDmgSpit` INT, 
`infDmgBoom` INT, 
`infDmgTankUp` INT, 
`infHunterDPs` INT, 
`infHunterDPDmg` INT, 
`infJockeyDPs` INT, 
`infDeathCharges` INT, 
`infCharges` INT, 
`infMultiCharges` INT, 
`infBoomsSingle` INT, 
`infBoomsDouble` INT, 
`infBoomsTriple` INT, 
`infBoomsQuad` INT, 
`infBooms` INT, 
`infBoomerPops` INT, 
`infLedged` INT, 
`infCommon` INT, 
`infSpawns` INT, 
`infSpawnSmoker` INT, 
`infSpawnBoomer` INT, 
`infSpawnHunter` INT, 
`infSpawnCharger` INT, 
`infSpawnSpitter` INT, 
`infSpawnJockey` INT, 
`infTankPasses` INT, 
`infTankRockHits` INT, 
`infCarsTriggered` INT, 
`infJockeyRideDuration` INT, 
`infJockeyRideTotal` INT, 
`infTimeStartPresent` INT, 
`infTimeStopPresent` INT, 
PRIMARY KEY  (`id`) 
);

CREATE TABLE IF NOT EXISTS `matchlog` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`map` varchar(64), 
`deleted` BOOLEAN, 
`result` INT, 
`steamid` varchar(32), 
`startedAt` INT, 
`endedAt` INT, 
`team` INT, 
PRIMARY KEY  (`id`) 
);

CREATE TABLE IF NOT EXISTS `players` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`name` varchar(128), 
`discord` varchar(48), 
`steamid` varchar(32), 
PRIMARY KEY  (`id`) 
);

CREATE TABLE IF NOT EXISTS `maps` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`map` varchar(128), 
`campaign` varchar(128), 
`round` INT, 
PRIMARY KEY  (`id`) 
);

CREATE TABLE IF NOT EXISTS `pvp_ff` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`round` INT, 
`team` INT, 
`map` varchar(64), 
`steamid` varchar(32), 
`deleted` BOOLEAN, 
`isSecondHalf` BOOLEAN, 
`victim` varchar(32), 
`damage` INT, 
PRIMARY KEY  (`id`) 
);

CREATE TABLE IF NOT EXISTS `pvp_infdmg` ( 
`id` INT NOT NULL auto_increment, 
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
`matchId` INT, 
`round` INT, 
`team` INT, 
`map` varchar(64), 
`steamid` varchar(32), 
`deleted` BOOLEAN, 
`isSecondHalf` BOOLEAN, 
`victim` varchar(32), 
`damage` INT, 
PRIMARY KEY  (`id`) 
);